'use client';

import { FileText, Download, Share2 } from 'lucide-react';
import SecurityScore from './SecurityScore';

interface ReportFinding {
  id: string;
  severity: 'critical' | 'high' | 'low' | 'info';
  title: string;
  line: number;
  description: string;
}

interface ReportContract {
  name: string;
  score: number;
  findings: ReportFinding[];
}

interface ReportPreviewProps {
  contracts: ReportContract[];
  title?: string;
  onExport?: () => void;
  onShare?: () => void;
}

const severityLabel: Record<string, string> = {
  critical: '🔴 Critical',
  high: '🟠 High',
  low: '🟡 Low',
  info: '🔵 Informational',
};

export default function ReportPreview({ contracts, title = 'Security Audit Report', onExport, onShare }: ReportPreviewProps) {
  const totalFindings = contracts.reduce((sum, c) => sum + c.findings.length, 0);
  const avgScore = contracts.length > 0
    ? Math.round(contracts.reduce((sum, c) => sum + c.score, 0) / contracts.length)
    : 0;
  const counts = {
    critical: contracts.reduce((s, c) => s + c.findings.filter((f) => f.severity === 'critical').length, 0),
    high: contracts.reduce((s, c) => s + c.findings.filter((f) => f.severity === 'high').length, 0),
    low: contracts.reduce((s, c) => s + c.findings.filter((f) => f.severity === 'low').length, 0),
    info: contracts.reduce((s, c) => s + c.findings.filter((f) => f.severity === 'info').length, 0),
  };

  return (
    <div className="card p-6 space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2 text-muted text-xs mb-1">
            <FileText className="w-4 h-4" />
            <span>Generated by SecurityPad</span>
            <span>•</span>
            <span>{new Date().toLocaleDateString()}</span>
          </div>
          <h2 className="text-xl font-bold">{title}</h2>
          <p className="text-sm text-muted mt-1">
            {contracts.length} contract{contracts.length !== 1 ? 's' : ''} analyzed • {totalFindings} findings
          </p>
        </div>
        <div className="flex gap-2">
          <button onClick={onExport} className="btn-primary text-xs flex items-center gap-1.5">
            <Download className="w-3.5 h-3.5" /> Export PDF
          </button>
          <button onClick={onShare} className="px-3 py-1.5 text-xs rounded border border-border text-muted hover:text-text hover:border-info transition-colors flex items-center gap-1.5">
            <Share2 className="w-3.5 h-3.5" /> Share
          </button>
        </div>
      </div>

      {/* Summary */}
      <div className="flex flex-wrap gap-6 items-center">
        <SecurityScore score={avgScore} size={100} />
        <div className="flex gap-4">
          <div className="text-center">
            <div className="text-2xl font-bold text-critical">{counts.critical}</div>
            <div className="text-xs text-muted">Critical</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold text-high">{counts.high}</div>
            <div className="text-xs text-muted">High</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold text-low">{counts.low}</div>
            <div className="text-xs text-muted">Low</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold text-info">{counts.info}</div>
            <div className="text-xs text-muted">Info</div>
          </div>
        </div>
      </div>

      {/* Contracts */}
      {contracts.map((contract, idx) => (
        <div key={idx} className="border border-border rounded-lg p-4 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold">{contract.name}</h3>
            <span className="text-sm text-muted">Score: {contract.score}/100</span>
          </div>
          {contract.findings.length === 0 ? (
            <p className="text-sm text-success">✓ No vulnerabilities detected</p>
          ) : (
            <div className="space-y-2">
              {contract.findings.map((f) => (
                <div key={f.id} className="flex items-start gap-2 p-2 bg-background rounded text-sm">
                  <span className="shrink-0">{severityLabel[f.severity].split(' ')[0]}</span>
                  <div>
                    <span className="font-medium">{f.title}</span>
                    <span className="text-muted ml-2">Line {f.line}</span>
                    <p className="text-muted text-xs mt-1">{f.description}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
